apiVersion: scheduling.kubefed.io/v1alpha1
kind: ReplicaSchedulingPreference
metadata:
  name: test-deployment
  namespace: test-namespace
spec:
  targetKind: FederatedDeployment
  totalReplicas: 9
  rebalance: true
  clusters:
    cluster1:
      minReplicas: 4
      maxReplicas: 6
      weight: 1
    cluster2:
      minReplicas: 4
      maxReplicas: 8
      weight: 2
